ad_box_homepage:
    path:     /
    defaults: { _controller: AdBoxBundle:Default:index }
    
index_page:
    path:     /index
    defaults: { _controller: AdBoxBundle:Admin:index }
    
login_page:
    path:     /login
    defaults: { _controller: AdBoxBundle:Security:login }

registerUserOne_page:
    path:     /registerUserOne
    defaults: { _controller: AdBoxBundle:Default:registerUserOne }

registerUserTwo_page:
    path:     /registerUserTwo
    defaults: { _controller: AdBoxBundle:Default:registerUserTwo }
    
registerClient_page:
    path:     /registerClient
    defaults: { _controller: AdBoxBundle:Default:registerClient }
    
registerAdmin_page:
    path:     /registerAdmin
    defaults: { _controller: AdBoxBundle:Default:registerAdmin }
    
registerZeus_page:
    path:     /registerZeus
    defaults: { _controller: AdBoxBundle:Default:registerZeus }
    
registerShopOwner_page:
    path:     /registerShopOwner
    defaults: { _controller: AdBoxBundle:Default:registerShopOwner }
    
media_page:
    path:     /mediaa
    defaults: { _controller: AdBoxBundle:Media:media }
    
    
calendar_page:
    path:     /calendar
    defaults: { _controller: AdBoxBundle:Admin:calendar}
#    
#media_create:
#    path:     /media/create
#    defaults: { _controller: AdBoxBundle:Media:new }
    
actualite_show:
    path:     /actualite/{idactualite}/actualite_show
    defaults: { _controller: AdBoxBundle:Actualites:show }
actualite_new:
    path:     /actualite/new
    defaults: { _controller: AdBoxBundle:Actualites:new }  
actualite_create:
    path:     /actualite/create
    defaults: { _controller: AdBoxBundle:Actualites:create }  
actualite_edit:
    path:     /actualite/{idactualite}/edit
    defaults: { _controller: AdBoxBundle:Actualites:edit } 
    methods: [GET,PUT]
    
actualite_update:
    path:     /actualite/{idactualite}/update
    defaults: { _controller: AdBoxBundle:Actualites:Update }
    methods: [GET,PUT]
actualite_delete:
    path:     /actualite/{idactualite}/delete
    defaults: { _controller: AdBoxBundle:Actualites:delete }
    methods: [POST,DELETE]
media_show:
    path:     /media/{id}/media_show
    defaults: { _controller: AdBoxBundle:Media:show }
media_new:
    path:     /media/new
    defaults: { _controller: AdBoxBundle:Media:new }  
media_create:
    path:     /media/create
    defaults: { _controller: AdBoxBundle:Media:create }  
media_edit:
    path:     /media/{id}/edit
    defaults: { _controller: AdBoxBundle:Media:edit } 
    methods: [GET,PUT]
    
media_update:
    path:     /media/{id}/update
    defaults: { _controller: AdBoxBundle:Media:Update }
    methods: [GET,PUT]
media_delete:
    path:     /media/{id}/delete
    defaults: { _controller: AdBoxBundle:Media:delete }
    methods: [POST,DELETE]
    
media_index:
    path:     /media
    defaults: { _controller: AdBoxBundle:Media:index }

admin_home:
    path:     /admin
    defaults: { _controller: AdBoxBundle:Admin:index }
client_home:
    path:     /client
    defaults: { _controller: AdBoxBundle:Client:index }
    
fos_user_client_registration_confirmed:
    pattern: /registrationC/confirmed
    defaults: { _controller: AdBoxBundle:Client:index }
    requirements:
        _method: GET

fos_user_admin_registration_confirmed:
    pattern: /registrationA/confirmed
    defaults: { _controller: AdBoxBundle:Admin:index }
    requirements:
        _method: GET
        
fos_user_zeus_registration_confirmed:
    pattern: /registrationZ/confirmed
    defaults: { _controller: AdBoxBundle:Zeus:index }
    requirements:
        _method: GET
        
fos_user_shopowner_registration_confirmed:
    pattern: /registrationS/confirmed
    defaults: { _controller: AdBoxBundle:ShopOwner:index }
    requirements:
        _method: GET
    

list_admins:
    path:     /listAdmins
    defaults: { _controller: AdBoxBundle:Admin:listAllAdmin }
    
find_admins:
    path:     /findAdmin/{id}
    defaults: { _controller: AdBoxBundle:Admin:findAdmins }

edit_admins:
    path:     /editAdmin/{id}
    defaults: { _controller: AdBoxBundle:Admin:editAdmin }

edit_clients:
    path:     /editClient/{id}
    defaults: { _controller: AdBoxBundle:Client:editClient }
    
list_clients:
    path:     /listClients
    defaults: { _controller: AdBoxBundle:Client:listAllClient }
    
list_ShopOwners:
    path:     /listShopOwners
    defaults: { _controller: AdBoxBundle:ShopOwner:listAllShopOwner }
    
edit_ShopOwners:
    path:     /editShopOwner/{id}
    defaults: { _controller: AdBoxBundle:ShopOwner:editShopOwner }