ad_box_homepage:
    path:     /
    defaults: { _controller: AdBoxBundle:Default:index }
    
index_page:
    path:     /index
    defaults: { _controller: AdBoxBundle:Admin:index }
    
login_page:
    path:     /login
    defaults: { _controller: AdBoxBundle:Security:login }

registerUserOne_page:
    path:     /registerUserOne
    defaults: { _controller: AdBoxBundle:Default:registerUserOne }

registerUserTwo_page:
    path:     /registerUserTwo
    defaults: { _controller: AdBoxBundle:Default:registerUserTwo }
    
registerClient_page:
    path:     /registerClient
    defaults: { _controller: AdBoxBundle:Default:registerClient }
    
registerAdmin_page:
    path:     /registerAdmin
    defaults: { _controller: AdBoxBundle:Default:registerAdmin }
    
registerZeus_page:
    path:     /registerZeus
    defaults: { _controller: AdBoxBundle:Default:registerZeus }
    
registerShopOwner_page:
    path:     /registerShopOwner
    defaults: { _controller: AdBoxBundle:Default:registerShopOwner }
    
media_page:
    path:     /media
    defaults: { _controller: AdBoxBundle:Media:media }
    
    
calendar_page:
    path:     /calendar
    defaults: { _controller: AdBoxBundle:Admin:calendar}
