ad_box_zeus:
    resource: "@AdBoxBundle/Controller/ZeusController.php"
    type:     annotation

ad_box_timelaps:
    resource: "@AdBoxBundle/Controller/TimelapsController.php"
    type:     annotation

ad_box_shop_owner:
    resource: "@AdBoxBundle/Controller/ShopOwnerController.php"
    type:     annotation

ad_box_shop:
    resource: "@AdBoxBundle/Controller/ShopController.php"
    type:     annotation

ad_box_reservation:
    resource: "@AdBoxBundle/Controller/ReservationController.php"
    type:     annotation

ad_box_pub:
    resource: "@AdBoxBundle/Controller/PubController.php"
    type:     annotation

ad_box_notification:
    resource: "@AdBoxBundle/Controller/NotificationController.php"
    type:     annotation

ad_box_media:
    resource: "@AdBoxBundle/Controller/MediaController.php"
    type:     annotation

ad_box_event_timelaps:
    resource: "@AdBoxBundle/Controller/EventTimelapsController.php"
    type:     annotation

ad_box_client:
    resource: "@AdBoxBundle/Controller/ClientController.php"
    type:     annotation

ad_box_box:
    resource: "@AdBoxBundle/Controller/BoxController.php"
    type:     annotation

ad_box_bid_client:
    resource: "@AdBoxBundle/Controller/BidClientController.php"
    type:     annotation

ad_box_bid:
    resource: "@AdBoxBundle/Controller/BidController.php"
    type:     annotation

ad_box_adresse:
    resource: "@AdBoxBundle/Controller/AdresseController.php"
    type:     annotation

ad_box_admin:
    resource: "@AdBoxBundle/Controller/AdminController.php"
    type:     annotation

ad_box_action_timelaps:
    resource: "@AdBoxBundle/Controller/ActionTimelapsController.php"
    type:     annotation

ad_box_action_event:
    resource: "@AdBoxBundle/Controller/ActionEventController.php"
    type:     annotation

ad_box_event:
    resource: "@AdBoxBundle/Controller/EventController.php"
    type:     annotation

ad_box_action:
    resource: "@AdBoxBundle/Controller/ActionController.php"
    type:     annotation

ad_box:
    resource: "@AdBoxBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
user_one_registration:
    path:  /register/user-one
    defaults: { _controller: AdBoxBundle:RegistrationUserOne:register }

user_two_registration:
    path:  /register/user-two
    defaults: { _controller: AdBoxBundle:RegistrationUserTwo:register }
    
user_client_registration:
    path:  /register/Client
    defaults: { _controller: AdBoxBundle:RegistrationUserClient:register }

user_admin_registration:
    path:  /register/Admin
    defaults: { _controller: AdBoxBundle:RegistrationUserAdmin:register }

user_zeus_registration:
    path:  /register/Zeus
    defaults: { _controller: AdBoxBundle:RegistrationUserZeus:register }
 
user_shopowner_registration:
    path:  /register/ShopOwner
    defaults: { _controller: AdBoxBundle:RegistrationUserShopOwner:register }
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /registerfos

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
